[project]
name = "mangochill-notebook"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "polars>=1.34.0",
  "python-dateutil>=2.9.0",
  "marimo[lsp,mcp]>=0.10.0",
  "altair>=5.5.0",
  "ruff>=0.14.1",
  "pint>=0.25",
]

[dependency-groups]
dev = ["basedpyright>=1.32.1"]
